/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWellnessRouteImport } from './routes/_authenticated/wellness'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWellnessIndexRouteImport } from './routes/_authenticated/wellness.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedWellnessRoutinesRouteImport } from './routes/_authenticated/wellness.routines'
import { Route as AuthenticatedWellnessMindRouteImport } from './routes/_authenticated/wellness.mind'
import { Route as AuthenticatedWellnessLearnRouteImport } from './routes/_authenticated/wellness.learn'
import { Route as AuthenticatedWellnessCoachRouteImport } from './routes/_authenticated/wellness.coach'
import { Route as AuthenticatedFinanceTradeRouteImport } from './routes/_authenticated/finance.trade'
import { Route as AuthenticatedFinanceNetworthRouteImport } from './routes/_authenticated/finance.networth'
import { Route as AuthenticatedFinanceMarketRouteImport } from './routes/_authenticated/finance.market'
import { Route as AuthenticatedFinanceInvestRouteImport } from './routes/_authenticated/finance.invest'
import { Route as AuthenticatedFinanceCoachRouteImport } from './routes/_authenticated/finance.coach'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWellnessRoute = AuthenticatedWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWellnessIndexRoute =
  AuthenticatedWellnessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWellnessRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedWellnessRoutinesRoute =
  AuthenticatedWellnessRoutinesRouteImport.update({
    id: '/routines',
    path: '/routines',
    getParentRoute: () => AuthenticatedWellnessRoute,
  } as any)
const AuthenticatedWellnessMindRoute =
  AuthenticatedWellnessMindRouteImport.update({
    id: '/mind',
    path: '/mind',
    getParentRoute: () => AuthenticatedWellnessRoute,
  } as any)
const AuthenticatedWellnessLearnRoute =
  AuthenticatedWellnessLearnRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => AuthenticatedWellnessRoute,
  } as any)
const AuthenticatedWellnessCoachRoute =
  AuthenticatedWellnessCoachRouteImport.update({
    id: '/coach',
    path: '/coach',
    getParentRoute: () => AuthenticatedWellnessRoute,
  } as any)
const AuthenticatedFinanceTradeRoute =
  AuthenticatedFinanceTradeRouteImport.update({
    id: '/trade',
    path: '/trade',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceNetworthRoute =
  AuthenticatedFinanceNetworthRouteImport.update({
    id: '/networth',
    path: '/networth',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceMarketRoute =
  AuthenticatedFinanceMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceInvestRoute =
  AuthenticatedFinanceInvestRouteImport.update({
    id: '/invest',
    path: '/invest',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCoachRoute =
  AuthenticatedFinanceCoachRouteImport.update({
    id: '/coach',
    path: '/coach',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/habits': typeof AuthenticatedHabitsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/wellness': typeof AuthenticatedWellnessRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/finance/coach': typeof AuthenticatedFinanceCoachRoute
  '/finance/invest': typeof AuthenticatedFinanceInvestRoute
  '/finance/market': typeof AuthenticatedFinanceMarketRoute
  '/finance/networth': typeof AuthenticatedFinanceNetworthRoute
  '/finance/trade': typeof AuthenticatedFinanceTradeRoute
  '/wellness/coach': typeof AuthenticatedWellnessCoachRoute
  '/wellness/learn': typeof AuthenticatedWellnessLearnRoute
  '/wellness/mind': typeof AuthenticatedWellnessMindRoute
  '/wellness/routines': typeof AuthenticatedWellnessRoutinesRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/wellness/': typeof AuthenticatedWellnessIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/finance/coach': typeof AuthenticatedFinanceCoachRoute
  '/finance/invest': typeof AuthenticatedFinanceInvestRoute
  '/finance/market': typeof AuthenticatedFinanceMarketRoute
  '/finance/networth': typeof AuthenticatedFinanceNetworthRoute
  '/finance/trade': typeof AuthenticatedFinanceTradeRoute
  '/wellness/coach': typeof AuthenticatedWellnessCoachRoute
  '/wellness/learn': typeof AuthenticatedWellnessLearnRoute
  '/wellness/mind': typeof AuthenticatedWellnessMindRoute
  '/wellness/routines': typeof AuthenticatedWellnessRoutinesRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/wellness': typeof AuthenticatedWellnessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/wellness': typeof AuthenticatedWellnessRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/finance/coach': typeof AuthenticatedFinanceCoachRoute
  '/_authenticated/finance/invest': typeof AuthenticatedFinanceInvestRoute
  '/_authenticated/finance/market': typeof AuthenticatedFinanceMarketRoute
  '/_authenticated/finance/networth': typeof AuthenticatedFinanceNetworthRoute
  '/_authenticated/finance/trade': typeof AuthenticatedFinanceTradeRoute
  '/_authenticated/wellness/coach': typeof AuthenticatedWellnessCoachRoute
  '/_authenticated/wellness/learn': typeof AuthenticatedWellnessLearnRoute
  '/_authenticated/wellness/mind': typeof AuthenticatedWellnessMindRoute
  '/_authenticated/wellness/routines': typeof AuthenticatedWellnessRoutinesRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/wellness/': typeof AuthenticatedWellnessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/ai'
    | '/calendar'
    | '/finance'
    | '/habits'
    | '/settings'
    | '/tasks'
    | '/wellness'
    | '/api/chat'
    | '/finance/coach'
    | '/finance/invest'
    | '/finance/market'
    | '/finance/networth'
    | '/finance/trade'
    | '/wellness/coach'
    | '/wellness/learn'
    | '/wellness/mind'
    | '/wellness/routines'
    | '/finance/'
    | '/wellness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/ai'
    | '/calendar'
    | '/habits'
    | '/settings'
    | '/tasks'
    | '/api/chat'
    | '/'
    | '/finance/coach'
    | '/finance/invest'
    | '/finance/market'
    | '/finance/networth'
    | '/finance/trade'
    | '/wellness/coach'
    | '/wellness/learn'
    | '/wellness/mind'
    | '/wellness/routines'
    | '/finance'
    | '/wellness'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/ai'
    | '/_authenticated/calendar'
    | '/_authenticated/finance'
    | '/_authenticated/habits'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/wellness'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/finance/coach'
    | '/_authenticated/finance/invest'
    | '/_authenticated/finance/market'
    | '/_authenticated/finance/networth'
    | '/_authenticated/finance/trade'
    | '/_authenticated/wellness/coach'
    | '/_authenticated/wellness/learn'
    | '/_authenticated/wellness/mind'
    | '/_authenticated/wellness/routines'
    | '/_authenticated/finance/'
    | '/_authenticated/wellness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wellness': {
      id: '/_authenticated/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthenticatedWellnessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wellness/': {
      id: '/_authenticated/wellness/'
      path: '/'
      fullPath: '/wellness/'
      preLoaderRoute: typeof AuthenticatedWellnessIndexRouteImport
      parentRoute: typeof AuthenticatedWellnessRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/wellness/routines': {
      id: '/_authenticated/wellness/routines'
      path: '/routines'
      fullPath: '/wellness/routines'
      preLoaderRoute: typeof AuthenticatedWellnessRoutinesRouteImport
      parentRoute: typeof AuthenticatedWellnessRoute
    }
    '/_authenticated/wellness/mind': {
      id: '/_authenticated/wellness/mind'
      path: '/mind'
      fullPath: '/wellness/mind'
      preLoaderRoute: typeof AuthenticatedWellnessMindRouteImport
      parentRoute: typeof AuthenticatedWellnessRoute
    }
    '/_authenticated/wellness/learn': {
      id: '/_authenticated/wellness/learn'
      path: '/learn'
      fullPath: '/wellness/learn'
      preLoaderRoute: typeof AuthenticatedWellnessLearnRouteImport
      parentRoute: typeof AuthenticatedWellnessRoute
    }
    '/_authenticated/wellness/coach': {
      id: '/_authenticated/wellness/coach'
      path: '/coach'
      fullPath: '/wellness/coach'
      preLoaderRoute: typeof AuthenticatedWellnessCoachRouteImport
      parentRoute: typeof AuthenticatedWellnessRoute
    }
    '/_authenticated/finance/trade': {
      id: '/_authenticated/finance/trade'
      path: '/trade'
      fullPath: '/finance/trade'
      preLoaderRoute: typeof AuthenticatedFinanceTradeRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/networth': {
      id: '/_authenticated/finance/networth'
      path: '/networth'
      fullPath: '/finance/networth'
      preLoaderRoute: typeof AuthenticatedFinanceNetworthRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/market': {
      id: '/_authenticated/finance/market'
      path: '/market'
      fullPath: '/finance/market'
      preLoaderRoute: typeof AuthenticatedFinanceMarketRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/invest': {
      id: '/_authenticated/finance/invest'
      path: '/invest'
      fullPath: '/finance/invest'
      preLoaderRoute: typeof AuthenticatedFinanceInvestRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/coach': {
      id: '/_authenticated/finance/coach'
      path: '/coach'
      fullPath: '/finance/coach'
      preLoaderRoute: typeof AuthenticatedFinanceCoachRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
  }
}

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceCoachRoute: typeof AuthenticatedFinanceCoachRoute
  AuthenticatedFinanceInvestRoute: typeof AuthenticatedFinanceInvestRoute
  AuthenticatedFinanceMarketRoute: typeof AuthenticatedFinanceMarketRoute
  AuthenticatedFinanceNetworthRoute: typeof AuthenticatedFinanceNetworthRoute
  AuthenticatedFinanceTradeRoute: typeof AuthenticatedFinanceTradeRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceCoachRoute: AuthenticatedFinanceCoachRoute,
  AuthenticatedFinanceInvestRoute: AuthenticatedFinanceInvestRoute,
  AuthenticatedFinanceMarketRoute: AuthenticatedFinanceMarketRoute,
  AuthenticatedFinanceNetworthRoute: AuthenticatedFinanceNetworthRoute,
  AuthenticatedFinanceTradeRoute: AuthenticatedFinanceTradeRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedWellnessRouteChildren {
  AuthenticatedWellnessCoachRoute: typeof AuthenticatedWellnessCoachRoute
  AuthenticatedWellnessLearnRoute: typeof AuthenticatedWellnessLearnRoute
  AuthenticatedWellnessMindRoute: typeof AuthenticatedWellnessMindRoute
  AuthenticatedWellnessRoutinesRoute: typeof AuthenticatedWellnessRoutinesRoute
  AuthenticatedWellnessIndexRoute: typeof AuthenticatedWellnessIndexRoute
}

const AuthenticatedWellnessRouteChildren: AuthenticatedWellnessRouteChildren = {
  AuthenticatedWellnessCoachRoute: AuthenticatedWellnessCoachRoute,
  AuthenticatedWellnessLearnRoute: AuthenticatedWellnessLearnRoute,
  AuthenticatedWellnessMindRoute: AuthenticatedWellnessMindRoute,
  AuthenticatedWellnessRoutinesRoute: AuthenticatedWellnessRoutinesRoute,
  AuthenticatedWellnessIndexRoute: AuthenticatedWellnessIndexRoute,
}

const AuthenticatedWellnessRouteWithChildren =
  AuthenticatedWellnessRoute._addFileChildren(
    AuthenticatedWellnessRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWellnessRoute: typeof AuthenticatedWellnessRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWellnessRoute: AuthenticatedWellnessRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
