/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai': typeof AuthenticatedAiRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/calendar'
    | '/finance'
    | '/habits'
    | '/tasks'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai'
    | '/calendar'
    | '/finance'
    | '/habits'
    | '/tasks'
    | '/api/chat'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai'
    | '/_authenticated/calendar'
    | '/_authenticated/finance'
    | '/_authenticated/habits'
    | '/_authenticated/tasks'
    | '/api/chat'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
